# Generated by Django 5.0.4 on 2024-05-03 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ansiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuestas', models.CharField(max_length=12)),
                ('fecha', models.DateTimeField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('nombreUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='depresion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=12)),
                ('fecha', models.DateTimeField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('nombreUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
