# Generated by Django 5.0.4 on 2024-05-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depresion',
            old_name='nombre',
            new_name='respuestas',
        ),
    ]
